### ISSUE TITLE
eutils

### ISSUE THREAD

**Issue by jonasstein** [mapmot/arduino-overlay#9]
Hi, thank you for working on the arduino ebuild. 
You likely need no eutils in this line, because you use EAPI 6
https://github.com/mapmot/arduino-overlay/blob/master/dev-embedded/arduino/arduino-1.8.5.ebuild#L8

**Comment by mapmot** [comment]
Thanks for the catch. You are probably right, but for the wrong reasons: eutils is not needed, because nothing in the ebuild calls make/make install - it's all either java/ant or insinto/doins.

**Comment by mapmot** [comment]
Fixed in [https://github.com/mapmot/arduino-overlay/commit/33c4f3fe2e6db703e77f42b60868506acdbff072](url)
